############# English navigation ##############

# main menu
[[main]]
name = "LaunchPad"
url = "/en/"
weight = 1
identifier = "home"

[[main]]
name = "About"
url = "/en/about"
weight = 2
    [[main]]
    parent = "About"
    name = "Terms & Conditions"
    url = "/en/terms-conditions"
    weight = 1

[[main]]
name = "Contact Us"
url = "/en/contact"
weight = 3

[[main]]
weight = 4
name = "Tutorials"
url = "/en/tutorials"

  [[main]]
  parent = "Tutorials"
  name = "GCDS Components"
  url = "/en/gcds-components"
