############# French navigation ##############

# main menu
[[main]]
name = "Rampe de Lancement"
url = "/fr/"
weight = 1
identifier = "home"

[[main]]
name = "A Propos"
url = "/fr/a-propos"
weight = 2
    [[main]]
    parent = "A Propos"
    name = "Termes & Conditions"
    url = "/fr/termes-conditions"
    weight = 1

[[main]]
name = "Contactez Nous"
url = "/fr/contact"
weight = 3

[[main]]
weight = 4
name = "Tutoriels"
url = "/fr/tutoriels"

  [[main]]
  parent = "Tutoriels"
  name = "GCDS Components"
  url = "/gcds-components"
